services:
  redis:
    image: redis:7
    container_name: dscc-redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    container_name: dscc-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./submission_store:/app/submission_store

  spark-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.spark
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: dscc-spark-api
    command: poetry run uvicorn spark.main:app --host 0.0.0.0 --port 9000
    ports:
      - "9000:9000"
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./submission_store:/app/submission_store
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GH_TOKEN=${GH_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.spark
    container_name: dscc-worker
    command: poetry run python jobs/worker.py
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./submission_store:/app/submission_store
